#!/bin/bash
# Copyright 2019, by J. Richard Barnette.  All Rights Reserved.
#

ant tests || exit $?
OUTFILE=$1
export CLASSPATH=test-classes:accounts.jar:$CLASSPATH
java jrb.accounts.TestAccountStore "$OUTFILE"
