#!/bin/bash
# Copyright 2019, by J. Richard Barnette.  All Rights Reserved.
#


ant tests || exit $?
echo
export CLASSPATH=test-classes:accounts.jar:$CLASSPATH
SED='
    /\/Test[^/]*\.java$/ !d
    s=tests/==
    s=\.java$==
    s=/=.=g
'
java org.junit.runner.JUnitCore $(sed "$SED" <tests-list)
