#!/bin/bash
# Copyright 2019, by J. Richard Barnette.  All Rights Reserved.
#


ant tests || exit $?
echo
export CLASSPATH=test-classes:accounts.jar:$CLASSPATH
SRC_TO_CLASS='
    s=tests/==
    s=\.java$==
    s=/=.=g
'
TESTS=( $(sed 's=^=tests/=' tests-list |
		xargs grep -l '^import org.junit.Test;' |
		xargs grep -l '^    @Test' |
		sed "${SRC_TO_CLASS}") )
java -ea org.junit.runner.JUnitCore "${TESTS[@]}"
