#!/bin/bash

ant tests || exit $?
echo
export CLASSPATH=test-classes:accounts.jar:$CLASSPATH
SED='
    /\/Test[^/]*\.java$/ !d
    s=tests/==
    s=\.java$==
    s=/=.=g
'
TESTS=( $(sed "$SED" < tests-list) )
for t in "${TESTS[@]}"
do
    echo $t
    java org.junit.runner.JUnitCore $t
done
